### ISSUE TITLE
the new .gitattributes prevents easy usage on Mac

### ISSUE THREAD

**Issue by tsupplis** [agn453/HI-TECH-Z80-C#10]
Files are automatically transformed and not transparently pushed back if using a Mac.

**Comment by agn453** [comment]
I commented in issue #9 regarding the keeping of CR-LF line termination and uppercase CP/M-style file names.

A git clone of this repository preserves them.  You can change them globally using the procedure described at

https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings

The current setup maintains CP/M formats (with the exception of the removal of text file end-of file marking with Ctrl-Z).  Files can also be used as-is under emulation (with RunCPM and zxcc) and imported/exported from the SIMH AltairZ80 simulator using the R and W commands.
