### ISSUE TITLE
Different Messages on zrrtcpm and zcrtcpm under dos

### ISSUE THREAD

**Issue by tsupplis** [agn453/HI-TECH-Z80-C#12]
on zcrtcpm.as:
bvmes:        defm    'This program requires a Z80 processor.'

on zrrtcpm.as:
bvmes:	defm	'This program requires a CP/M on Z80.'

I would recommend the latter personally.

**Comment by agn453** [comment]
Agreed.  I'm going to change your wording slightly to

```
This CP/M program requires a Z80 CPU.
```

(or "Z280 MPU") for the Z280 variant.

**Comment by agn453** [comment]
Modules updated.  Resolved.
