### ISSUE TITLE
OVERLAY.H references missing STDINT.H

### ISSUE THREAD

**Issue by agn453** [agn453/HI-TECH-Z80-C#17]
The overlay header file references a non-existent stdint.h (what I thought was a C++ header).

I have Ron Murray's original HTC-OVR distribution and this doesn't include this file or reference.

@tsupplis Is there a stdint.h for HI-TECH C somewhere?

**Comment by tsupplis** [comment]
sorry for that @agn453, forgot I add it and did not push it to your project 🙁

[stdint.zip](https://github.com/agn453/HI-TECH-Z80-C/files/5795498/stdint.zip)

https://github.com/tsupplis/zxcc-htc/blob/master/stdint.h

**Comment by agn453** [comment]
Thanks
