### ISSUE TITLE
Small feedback on the new C.C

### ISSUE THREAD

**Issue by tsupplis** [agn453/HI-TECH-Z80-C#18]
A couple of very minor bits I spotted when merging back all your C.C changes. Almost vanilla now apart from the end of -Y

1. Should options contain:
```
-E      Name of the executable output.
```

2. Also you fixed a good couple of -<lowercase> in the $EXEC.$$$ generation but a few -o and -c are still there
```
Line 755:         vec[i++] = strcat(strcpy(cbuf, "-C"), crtmp);
Line 449:         flgs[flg_idx++] = strcat(strcpy(xalloc(strlen(l_dot_obj)+3), "-o"),
```
Not a cause for concern on clean CP/M but on emulators it may trip them

**Comment by agn453** [comment]
Added -E description, adjusted the options (and missing test for existence of the OPTIONS file)
