### ISSUE TITLE
LIBC#####.LIB filename exceeds 8.3 character limit

### ISSUE THREAD

**Issue by b1ackmai1er** [agn453/HI-TECH-Z80-C#20]
Hi,

I presume the \dist directory is what is required to be transferred to CP/M, in which case I encountered this issue.

Regards Phil.

**Comment by b1ackmai1er** [comment]
Hi, I found the reference to the # numbering scheme and now realize that I do not need to include these, so will close this issue.

Thanks.

**Comment by agn453** [comment]
I'm going to remove all the files with '#' in their name.  Yes, it is confusing!

Tony

**Comment by b1ackmai1er** [comment]
thanks tony. also /dist is missing  overlay.h file

**Comment by agn453** [comment]
I've added a copy of overlay.h to the distribution
