### ISSUE TITLE
new C.C frontend not running on ZXCC

### ISSUE THREAD

**Issue by tsupplis** [agn453/HI-TECH-Z80-C#22]
The new front end is still not working on ZXCC. The output of the $$$ file is corrupted. 

This is the previous problem I was raising linked to the initial size adjustment.

**Comment by tsupplis** [comment]
For the moment I keep the two lines in write out for letting it work.
/*            if (fc->fsize < fc->rwp) 
                fc->fsize = fc->rwp;*/
That makes it work. I just need to create a counter proof and understand better its effect.

**Comment by tsupplis** [comment]
Can you double check with your version of zxcc? The reason why it is quite important is zxcc is quite wide spread and was specially designed for working with HTC C

Also the link->linkq change breaks it requiring a change of zxcc. What do you recommend there? I created a repo for my version of it base on John Elliot original source code .

**Comment by agn453** [comment]
I'm seeing the same issue with zxcc 0.5.7 on my mac mini (running macOS Catalina 10.15.7)

The latest compiler is copied to the right place -

```
maxi:dist tony$ # from the dist directory
maxi:dist tony$ for f in *.COM; do g=`echo $f | tr "[:upper:]" "[:lower:]"`; echo $g; cp -p $f ~/lib/cpm/bin80/$g ; done
maxi:dist tony$ for f in LIBC.LIB LIBF.LIB LIBOVR.LIB; do g=`echo $f | tr "[:upper:]" "[:lower:]"`; echo $g; cp -p $f ~/lib/cpm/lib80/$g ; done
maxi:dist tony$ for f in `ls -1 *.H *.OBJ | grep -v "#"`; do g=`echo $f | tr "[:upper:]" "[:lower:]"`; echo $g; cp -p $f ~/lib/cpm/include80/$g ; done

maxi:dist tony$ # using the original compiler front-end
maxi:dist tony$ cd
maxi:~ tony$ zxc -o -v t.c
HI-TECH C COMPILER (CP/M-80) V3.09
Copyright (C) 1984-87 HI-TECH SOFTWARE
0:CPP -DCPM -DHI_TECH_C -Dz80 -Ic: -I P:T.C $CTMP1.$$$
0:P1 $CTMP1.$$$ $CTMP2.$$$ $CTMP3.$$$
0:CGEN $CTMP2.$$$ $CTMP1.$$$
0:OPTIM $CTMP1.$$$ $CTMP2.$$$
0:ZAS -J -N -oT.OBJ $CTMP2.$$$
ERA $CTMP1.$$$
ERA $CTMP2.$$$
ERA $CTMP3.$$$
0:LINQ -Z -Ptext=0,data,bss -C100H -OT.COM CRTCPM.OBJ T.OBJ LIBC.LIB
ERA T.OBJ
ERA $$EXEC.$$$

maxi:~ tony$ ls -l t.*
-rw-r--r--+ 1 tony  staff    128 Jan 17 07:17 t.c
-rw-------+ 1 tony  staff  12288 Jan 17 07:44 t.com
maxi:~ tony$ # The resulting t.com doesn't work
maxi:~ tony$ zxcc t

maxi:~ tony$ # but it looks ok
maxi:~ tony$ zxcc zsid t.com
ZSID VERS 1.5
NEXT  PC  END
3100 0100 DBFF
#l100 
  0100  EX   DE,HL
  0101  INC  B
  0102  EX   DE,HL
  0103  JP   012D
  0106  CP   B
  0107  NOP  
  0108  ADD  HL,BC
  0109  CP   D
  010A  JP   PE,CD2B
  010D  LD   HL,01B8
  0110  LD   C,H
# g0

maxi:~ tony$ # Trying the lastest front-end
maxi:~ tony$ zxcc c309-8 -o -v t.c
P:T.C: 2: Can't find include file stdio.h

maxi:~ tony$ 
```

Something weird - I suspect the start-up code in crtcpm.obj - since the original compiler output with the new libraries and start-up module doesn't produce an executable program that runs under zxcc.

**Comment by agn453** [comment]
That last trying to run c309-8.com was wrong.

Renaming c309-8.com in the ~/lib/cpm/bin80 to c.com produces -

```
maxi:~ tony$ zxc -o -v t.c
0:CPP -DCPM -DHI_TECH_C -DZ80 -Ic: -I P:T.C $CTMP1.$$$
0:P1 $CTMP1.$$$ $CTMP2.$$$ $CTMP3.$$$
0:CGEN $CTMP2.$$$ $CTMP1.$$$
0:OPTIM $CTMP1.$$$ $CTMP2.$$$
0:ZAS -J -N -OT.OBJ $CTMP2.$$$
ERA $CTMP1.$$$
ERA $CTMP2.$$$
ERA $CTMP3.$$$
ERA $CTMP5.$$$
0:LINQ -Z -Ptext=0,data,bss -C100H -OT.COM CRTCPM.OBJ T.OBJ LIBC.LIB
ERA
Fmt err

maxi:~ tony$
```

**Comment by agn453** [comment]
> Also the link->linkq change breaks it requiring a change of zxcc. What do you recommend there? I created a repo for my version of it base on John Elliot original source code .

I changed the source-code for zxcc's zxlink command to invoke linq.com (instead of link.com).  That means i can have both the HI-TECH C linker and the Digital Research linker (link.com) in the zxcc ~/lib/cpm/bin80 folder (or the /usr/local/lib/cpm/bin80 folder if you built zxcc without specifying a --prefix option)

**Comment by tsupplis** [comment]
Ok done deal for linq.com
Interesting story about the bootstrap. I will carry on investigating.

**Comment by agn453** [comment]
I found that ZXCC was not returning the correct error code in response to a BDOS Call RSX (function 60).
This was causing console I/O to assume it was being processed via the non-existent PIPEMGR RSX.

When looking into the long command line problem, I found ZXCC's processing of a BDOS Read Console Buffer (function 10) would treat a buffer address length byte value greater than 127 as negative.  Changing it to use 'unsigned byte' to access the buffer has fixed this.

Also, I have fixed zxc option processing for the HI-TECH C ones that have a filename/directory parameter (-e -f -i -m -cr).

You'll find my updates for ZXCC in the https://github.com/agn453/ZXCC repository.

Compilations under ZXCC now work correctly - except when the verbose (-v) option is specified on the zxc command-line.

I'm still trying to track down a file corruption of the $$exec.$$$ file that only occurs under ZXCC if the -v option is specified to zxc.

**Comment by tsupplis** [comment]
Super cool. thank you so much. Will regress test the bdos(10) call. But interestingly all the fixes you did where already applied on my project https://github.com/tsupplis/zxccp (RSX, compiler warnings). The corruption of the $$exec.$$$ is actually the initial problem.

**Comment by agn453** [comment]
Thanks to Mark Ogden, ZXCC has had its "exact file size" implementation corrected to match that used by Jon Saxton and in HI-TECH C.  This corrects this issue.  You'll need to get the latest ZXCC updates from https://github.com/agn453/ZXCC (which now also support running under Microsoft Windows - both Cygwin and as command-line programs compiled by Visual Studio).
