### ISSUE TITLE
Work related to Hi-tech C

### ISSUE THREAD

**Issue by b1ackmai1er** [agn453/HI-TECH-Z80-C#26]
FYI https://groups.google.com/g/comp.os.cpm/c/fe3vQ16Fn0I

https://github.com/nikitinprior/dlibr

Best Wishes Phil

**Comment by agn453** [comment]
Thanks Phil.

I saw the message on comp.os.cpm - and there's a pointer to the object librarian reconstruction in this repository's README.

Andrea Nikitin and friends have also been busy with reconstructing the source to the code generation (cgen) and preprocessor (cpp) too.  There's links to these in the README as well.

Tony
