### ISSUE TITLE
Hi-Tech C MSDOS v7.80

### ISSUE THREAD

**Issue by feilipu** [agn453/HI-TECH-Z80-C#28]
Hi Tony, I've just posted some [benchmarks with the MSDOS version of v7.80](https://github.com/z88dk/z88dk/wiki/Benchmarks).

As the compiler was lent to me, and we don't know whether it is in public domain, I won't publish the code (yet).
I tried to reach the Hi-Tech contacts in the manual, including phone and web, but they're all dead ends.

Did you know someone at Hi-Tech who could provide guidance on the release state of the final Hi-Tech C MSDOS v7.80pl2 professional development system?

**Comment by agn453** [comment]
Hi Phillip,

As far as I know the MS-DOS cross compiler with the HPDZ development environment is not in the public domain.  Hi-TECH sold the rights for their compilers to Microchip Technology and they subsequently went
on to develop other cross-compilers.  Only the version that I have put up at https://github.com/agn453/HI-TECH-Z80-C-Cross-Compiler has been released.  The facebook Zilog Z80 DIY group has the posting by Chris A Hills is where this was announced.

Tony

**Comment by feilipu** [comment]
Thanks Tony.
Good to have that information.
My thought process had reached a similar conclusion.
It is so good that if it were abandonware, many people more would be using it.

**Comment by agn453** [comment]
I have a version of HITECH C MS-DOS V7.60 too (it requires a license key to install).  I found it
corrects some issues with code generation that can be seen under the CP/M Z80 version 3.09 and
is broken for some others (e.g. it won't compile the latest C309-11.C front-end source code).

**Comment by feilipu** [comment]
Yes, there is a key required to install the `HPDZ`, I guess typical of most MSDOS software of that vintage.

At [z88dk](https://github.com/z88dk/z88dk) we found too that v7.50 had issues, mainly with floating point that stopped most benchmarks from running successfully. But the last (?) version v7.80pl2 has resolved almost all those issues. The resulting code is compact and very fast, doing well on [the benchmarks](https://github.com/z88dk/z88dk/wiki/Benchmarks).

**Comment by feilipu** [comment]
Just a thought, if you want to test the v3.09 updates you're releasing against known code, then the [benchmarks](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/EXAMPLES/benchmarks) and examples form a good additional test set.
