### ISSUE TITLE
Undefined symbols with build 13 ( _open, _fseek, _creat, __filbuf)

### ISSUE THREAD

**Issue by mobra66** [agn453/HI-TECH-Z80-C#34]
When compiling with build 13, something seems to be wrong in LIBC.LIB when using the -n switch, see below session from CP/M 2.2 system. If I copy LIBC.LIB from build 12, it works without errors. If I remove the -n switch it also works.
The test program is a very simple hello world file.

```
#include <stdio.h>

void main(void) {
  printf("Hello...");
}

```
```
D>c -v -o -n hello.c
Hi-Tech Z80 C Compiler (CP/M-80) V3.09-13
Copyright (C) 1984-87 HI-TECH SOFTWARE
Updated from https://github.com/agn453/HI-TECH-Z80-C
0:CPP -DCPM -DHI_TECH_C -Dz80 -I HELLO.C $CTMP1.$$$
0:P1 $CTMP1.$$$ $CTMP2.$$$ $CTMP3.$$$
0:CGEN $CTMP2.$$$ $CTMP1.$$$
0:OPTIM $CTMP1.$$$ $CTMP2.$$$
0:ZAS -J -N -OHELLO.OBJ $CTMP2.$$$
ERA $CTMP1.$$$
ERA $CTMP2.$$$
ERA $CTMP3.$$$
ERA $CTMP5.$$$
0:LINQ -Z -Ptext=0,data,bss -C100H -OHELLO.COM NRTCPM.OBJ HELLO.OBJ LIBC.LIB
undefined symbols:
_open
_fseek
_creat
__filbuf
ERA $$EXEC.$$$
```

**Comment by agn453** [comment]
The change to actual file size includes code to access the system environment file ENVIRON and this is causing the undefined symbol diagnostic. There is an ordering constraint for one-pass linking of LIBC.LIB.

As a work-around, please try adding an -LC to the compiler command.  This will cause a second pass of LIBC.LIB during linking to resolve the references.

I need to go through the library module ordering to resolve this when I get some free time.

**Comment by tsupplis** [comment]
Hi, I fixed the problem by adding a ref to getenv in the bootstrap crt ... I found reordering almost mission impossible as it creates a circular dependency between getenv and file management. Maybe it helps....
The code of zxcc-htc is as aligned as possible with your code i.e. 99.99% apart from the c compiler driver.

https://github.com/tsupplis/zxcc-htc/blob/master/zcrtcpm.as
https://github.com/tsupplis/zxcc-htc/blob/master/rcrtcpm.as
```
...
	psect	text
	defs	100h		;Base of CP/M's TPA

	global	start,_main,_exit,__Hbss, __Lbss, __argc_, __z3env, startup
        global  __piped,__initrsx, _getenv

start:	       ; DOS Protection	8080/Z80	x86
		       ; ---------  --------------------
...
```

**Comment by agn453** [comment]
Yep - there's a circular reference!

I'm reluctant to add getenv as an external for the start-up module (since it would cause every compiled
program to include the file I/O routines).

I may revise the way to determine the exact file size convention and not use the EXACT environment variable.

Perhaps a global variable that is modified explicitly when a user desires ISX/ISIS mode.
The default can be set according to whether it's running under CP/M 3 or not (defaults to DosPlus or none) by a few lines of code in the crt start-up module.

**Comment by agn453** [comment]
I have removed the EXACT environment variable check and re-implemented this using a global variable
that's tested by the start-up module (e.g. CRTCPM.OBJ - source is in cpm/ZCRTCPM.AS).

This resolves the circular reference issue in the C libraries (LIBC.LIB and LIB280C.LIB) when linking.

The commit ID is 939b7a052d5b5a4fd3b9bf817a5264e3702da5c1 and the version/release has been updated to V3.09-14.

**Comment by mobra66** [comment]
Thank you for rapid response! I can confirm that build 14 is working as expected in my case too.
