### ISSUE TITLE
Can't execute $EXEC

### ISSUE THREAD

**Issue by ProgrammingCube** [agn453/HI-TECH-Z80-C#35]
This has been an issue for some time, but I can't really figure out whats up.

I'm using romwbw and cp/m, and whenever I try to invoke the compiler from another drive, I get this error:

`I>E:c309 -v main.c`
`HI-TECH C COMPILER (CP/M-80) V3.09`
`Copyright (C) 1984-87 HI-TECH SOFTWARE`
`Can't execute $EXEC`
`I>`
What causes this? Is there a way to fix this, so I don't have to manually copy everything over to the hi tech drive every time I want to compile?

**Comment by drawkula** [comment]
Check: https://github.com/agn453/HI-TECH-Z80-C/blob/master/doc/HTCZ80.TXT#L8683-L8707

That ™worked for me™ on RunCPM (an emulator).

**Comment by ProgrammingCube** [comment]
> Check: https://github.com/agn453/HI-TECH-Z80-C/blob/master/doc/HTCZ80.TXT#L8683-L8707
> 
> That ™worked for me™ on RunCPM (an emulator).

Worked like magic!
Man that manual is long lol

**Comment by agn453** [comment]
HI-TECH C checks a HITECH environment variable to override the default location for its files.  The default place it checks is the current drive/user and drive A: in user area 0.

if you create a file on the default drive called ENVIRON containing a line like

HITECH=0:C:

then the compiler will look in user area 0 on drive C:

You  can also place the ENVIRON file in user 0 on drive A: (and under CP/M 3 it can also be in a location in the search path that you set using the SETDEF command - usually run from the start-up PROFILE.SUB file).

Another TMP environment variable defines the drive used for temporary files for a compilation.  On my system, drive M: is a ram drive, so I also include

TMP=M:

as a second line in the ENVIRON file to take advantage of the faster accessed drive.  Note that you cannot specify a user area for TMP - it always uses the current default user number.

**Comment by agn453** [comment]
> This has been an issue for some time, but I can't really figure out whats up.
> 
> I'm using romwbw and cp/m, and whenever I try to invoke the compiler from another drive, I get this error:
> 
> `I>E:c309 -v main.c` `HI-TECH C COMPILER (CP/M-80) V3.09` `Copyright (C) 1984-87 HI-TECH SOFTWARE` `Can't execute $EXEC` `I>` What causes this? Is there a way to fix this, so I don't have to manually copy everything over to the hi tech drive every time I want to compile?

As an aside, when you install the compiler, you should rename the main HI-TECH driver program from e.g. C309-14.COM to C.COM to get the latest features.  Then you can invoke the compiler using the C command.  The supplied C309.COM is the original unmodified compiler without feature updates.
