### ISSUE TITLE
Cannot sseem to include libraries on different drive

### ISSUE THREAD

**Issue by ProgrammingCube** [agn453/HI-TECH-Z80-C#37]
I try using -I 0:C: to tell hitech c to look at drive c for includes, but nothing works. How do I do this? I'm compiling source on a separate drive.

**Comment by agn453** [comment]
The command line argument parser is rather primitive for CP/M and uses a space
as a delimiter.

To specify an include location, don't prefix it by a space - for example

```c -i0:a: -o -v test.c```

By default, the compiler will look in user area 0 on drive A: for the system include
files and object libraries.

You can also create a file called ```ENVIRON.``` on the source-file drive to override
the default, or have a system-wide one in ```0:A:ENVIRON.```.

This file may contain lines like the following to specify the location of the
HI-TECH files - for example

```
HITECH=0:C:
TMP=M:
```

for distribution files on drive C: in user area 0, (and to create temporary
files on a RAMdrive - drive M: .  NB; you can't specify a user area for TMP).

Details are in the Users Manual at
https://github.com/agn453/HI-TECH-Z80-C/blob/master/doc/Hi-Tech-Z80-1989-october.pdf
in section 1.6 Reconfiguring.

P.S.  You didn't specify which version of CP/M you are using.  With CP/M Plus you can
use the SETDEF command to set a search path for commands so you won't need to
specify the drive letter to invoke the compiler.
