### ISSUE TITLE
Resulting com files bigger than original compiler

### ISSUE THREAD

**Issue by sgjava** [agn453/HI-TECH-Z80-C#40]
I'm seeing resulting com files that are at least 10K bigger in some instances. Is there a reason for that? CP/M has a small TPA, so every byte counts. I'm using the same build process and code.

I tried the original c.com and had the same issue. I'm wondering if it has something to do with one of the libraries?

Tested with original HTC and sizes are back to normal. What I noticed is libc.lib is throwing an undefined symbols error with `_close`. I think you said you reordered stuff in that lib. I'm not sure what I can test on my side to see why resulting com files are bigger.

**Comment by agn453** [comment]
The updated libraries now default to including the enhanced version of getargs() (which adds wild card argument support) and I/O redirection using pipes via PIPEMGR.  If you do not require these, use the -N command option (or link with the NRTCPM.OBJ startup module). The close() routine adds support for exact file sizes and references a variable in the new startup module - so if you wish to revert to the original libraries, you’ll need to revert the startup object module (CRTCPM.OBJ) too.

A linker map (-Mfile.map) will show the library modules included and their sizes.

The floating point version of printf() is also larger than the one in LIBC.LIB (this is loaded when you use -LF).

**Comment by sgjava** [comment]
Ah, makes complete sense. I wonder if there are other modules you can weed out? I'm going for super compact since I have to use TPA bank for code and screen memory (direct writes to the video chip). https://github.com/sgjava/c3l#vic-memory-management-in-cpm Anyways, this accomplishes why I need which it to trim down libc stuff.

**Comment by sgjava** [comment]
Yes, so -n removes about 7K. What's involved in reverting to CRTCPM.OBJ? I'm noticing on program exit I cannot run the next program sometimes. Were there any changes that would affect program exit?

**Comment by agn453** [comment]
To revert to the original CRTCPM.OBJ you'll need to replace the one from this repository with the one from the original V3.09 distrubution kit (as well as the LIBC.LIB and LIBF.LIB).  NB: I don't include the unmodified distribution files in the repo.

Changes were made to set the exit status to work with CP/M Plus's SUBMIT which has extended error capabilities.  I can't remember exactly - but prior to this I think the exit status was written to a memory location at 0080h.  Is this where your programs are looking?

**Comment by sgjava** [comment]
I don't do anything special when main() completes. I have several programs and it seems the second run always hangs (no matter the order I run them in). I was kind of hoping for bug fixes like memset, ENVIRON, etc. without the additional functionality that increases memory footprint. LIBF is fine since I don't really use floating point math.

**Comment by agn453** [comment]
If you're able to narrow down the cause of the hangs (i.e. provide a demonstation program with the symptoms) - please open another issue.  I've not had any other reports like this.

I have found using a simulator that both allows breakpoints and can keep a history of program execution can help trace an such an issue.  I've used the SIMH AltairZ80 emulator and run the CP/M emulation until the hang, then breaking out to view the CPU history (instuctions, registers and flags).  It can also dump out areas of memory that may have been overwritten, and you can set breakpoints and single-step the simulation.

You can get prebuilt kits for SIMH AltairZ80 from Peter Scorn's site at https://schorn.ch/altair.html  or the full range of simulators for https://github.com/open-simh/simh that run under Windows, macOS and Linux.

**Comment by sgjava** [comment]
I'll send you an email. It could be specific to C128 CP/M, but the original HTC 3.09 doesn't have the issues. I'm doing weird stuff like using the TPA for video memory, so I'm not discounting that.
