### ISSUE TITLE
I'm getting a "can't create testprg.obj"

### ISSUE THREAD

**Issue by sgjava** [agn453/HI-TECH-Z80-C#42]
I've been splitting my library into individual modules and compile and libr goes fine. When I try `c -o -x -i0:d: testprg.c 0:d:libtest.lib 0:a:libc.lib` I get `can't create testprg.obj` without any context. Docs do not really tell you why this happens. The lib is about 45K, but libc is bigger than that.

**Comment by sgjava** [comment]
This was caused by myz80 d: which is a memory disk. When I switched to another empty drive it worked. Leaving the bread crumb for someone else to discover. Too bad it doesn't tell you why in the error.

**Comment by agn453** [comment]
My first response to “can’t create” a file would be to check if there is sufficient space and free directory entries on the default drive.  A CP/M plus command like SHOW [USE will display the number of free directory entries.

Glad you worked it out yourself though.

As for better error messages, I’ve been considering rebuilding the compiler modules from the reconstructed source files (by Andrea Nikitin and Mark Ogden).  Some more informative messages could be added - but at the expense of reducing memory available to do compiles.  I just haven’t had time or the will to tackle this while I’m recovering from lymphoma.  Hopefully I’ll get to this soon.

**Comment by sgjava** [comment]
I understand, you just need something that says these are the 3 things to check :) I probably knew this 30 years ago when I was building a large lib like now.
