### ISSUE TITLE
Can you detect if include defined?

### ISSUE THREAD

**Issue by sgjava** [agn453/HI-TECH-Z80-C#44]
Something like:

```
#ifndef _HITECH_H
#define _HITECH_H
#endif
```

**Comment by sgjava** [comment]
Answering my own question here:

```
#ifndef _HITECH_H
#define _HITECH_H
#include "hitech.h"
#endif
```

This will stop recursion and prevent out of memory errors.

**Comment by agn453** [comment]
If you look at the system include files you will see this style of conditional is used too.

Tony

**Comment by sgjava** [comment]
Yep, otherwise OOM errors. I just didn't know if the pre processor generated defines for includes. I did it the old school way.
