### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by sgjava** [agn453/HI-TECH-Z80-C#45]
Using submit to build library and then apps that rely on library. I first get something like uchar undefined even though hitech.h is included. No sure if my headers are too big, but I'm using ifndef to make sure they are loaded only one time. If I compile the same way without submit it builds. Are there any hints to making larger apps compile?

**Comment by agn453** [comment]
Submit loads itself into memory and takes up about 2K of memory.

For example on my CP/M 3 system -

```
10E>testver
E:TESTVER  COM
CP/M BDOS Version (3.1)
Machine (MCS80/Z80)
BDOS Address (0xF200)
BIOS Address (0xF800)
TPA Size (60.2K)
Using DOS Plus exact file size mode

10E>testver.sub
E:TESTVER  SUB
C:SUBMIT   COM  (User 0)

10E>testver
E:TESTVER  COM
CP/M BDOS Version (3.1)
Machine (MCS80/Z80)
BDOS Address (0xEA00)
BIOS Address (0xF800)
TPA Size (58.2K)
Using DOS Plus exact file size mode
```

If you want to get more space, then you could try installing something like ZXCC on a Linux/macOS/Windows machine and run your builds from there.  On my mac mini it gives a 63K TPA -

```
maxi:test tony$ zxcc testver
CP/M BDOS Version (3.1)
Machine (MCS80/Z80)
BDOS Address (0xFE00)
BIOS Address (0xFF00)
TPA Size (63.2K)
```

You can get ZXCC from my repo at https://github.com/agn453/ZXCC

Tony

PS:  The source for testver is here https://github.com/agn453/HI-TECH-Z80-C/blob/master/test/TESTVER.C

**Comment by sgjava** [comment]
I'm using MyZ80 ZP/M 3 and I think it has 59K TPA. I found the issue though. In Eclipse you can organize includes and it added stdio.h for some reason. Once I removed that the program compiled. The main thing is keep your functions small since they are loaded into memory during compile.

All the info above is good for future reference.
