### ISSUE TITLE
Problem with strings > 255 characters in size

### ISSUE THREAD

**Issue by ghost** [agn453/HI-TECH-Z80-C#7]
There seems to be a problem with either initializing or printing (printf) strings that are longer than 255 characters. The example code below initializes a string with 256 characters. When printing the string using printf(), only the first three characters are being displayed and the rest of the string is being omitted.

If you shorten the sting by exactly one (1) character to match 255 characters, the string is being displayed correctly.

I don't know wether this a problem with the array initializer or with the printf function. But it is reproducible and also affects arrays of strings (e.g. char *text[]; ).

My setup is a RC2014 running RomWBW and CP/M 3. The issue is also showing up on CP/M 2.2.

Example code:
```

#include <stdio.h>

/* initialize 256 bytes of text */
char test[500] = { 
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAX \
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY"
};

int main() {
   printf("len: %d\n", strlen(test));
   printf("string: %s\n", test);
   return 0;
}
```

**Comment by tsupplis** [comment]
currently the implementation in uchar supports only 255 length character indeed. This is currently a limitation of the implementation.

```
_doprnt(file, f, a)
FILE *	file;
register char *		f;
int *		a;
{
	char	c;
	uchar	fill, left;
	uchar	i;
	uchar	base, width, prec, sign, len;
```

I think the following change would fix it ... to be tested.

```
       unsigned int	i;
       unsigned char	base, width, prec, sign;
       unsigned int    len;
```

**Comment by tsupplis** [comment]
Quick check, the problem solution above seems to work

**Comment by ghost** [comment]
This is good news, as I am writing a text adventure game and need a few more characters in strings for my room descriptions, heh. Is this someting I can fix myself as well (and if so, how?) or will you - after some more testing - provide an updated release?

**Comment by tsupplis** [comment]
Proposed PR: https://github.com/agn453/HI-TECH-Z80-C/pull/8

**Comment by agn453** [comment]
I merged and updated @tsupplis suggested change from #8 . Seems to fix this issue.

**Comment by ghost** [comment]
Thank you very much!
